version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=db
      - POSTGRES_USERNAME=postgres

volumes:
  db_data:
  gem_cache:
  redis_data: